### ISSUE TITLE
Build path issue: s2i executable is needed and not on your path.

### ISSUE THREAD

**Issue by vinomaster** [IBM-Blockchain-Identity/indy-ssivc-tutorial#1]
Anyway of improving this experience?

./manage.sh build
The s2i executable is needed and not on your path.
It can be downloaded from here: https://github.com/openshift/source-to-image
Make sure you place it in a directory on your path.

On a Mac this is a start: brew install source-to-image

**Comment by brycecurtis** [comment]
Dependencies section added to readme with information to download and install s2i.
