### ISSUE TITLE
Building Von Network

### ISSUE THREAD

**Issue by andrewBSTan** [IBM-Blockchain-Identity/indy-ssivc-tutorial#11]
After doing the git clone step, I get stuck at VON Network build stage.  Any idea why?  It keep saying no space on device.  Any help will be appreciated as I am trying to get this up and running in my MacBook for a local presentation on this Friday Asia hours.

Ign:34 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages
Ign:35 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse all Packages
Err:36 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages
  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.149 80]
Ign:37 http://archive.ubuntu.com/ubuntu xenial-backports/main all Packages
Ign:38 http://archive.ubuntu.com/ubuntu xenial-backports/restricted amd64 Packages
Ign:39 http://archive.ubuntu.com/ubuntu xenial-backports/restricted all Packages
Ign:40 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages
Ign:41 http://archive.ubuntu.com/ubuntu xenial-backports/universe all Packages
Ign:42 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse amd64 Packages
Ign:43 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse all Packages
Reading package lists...
W: The repository 'http://security.ubuntu.com/ubuntu xenial-security Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports Release' does not have a Release file.
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/universe/source/Sources  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.91.26 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/universe/source/Sources  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.149 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/source/Sources  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.149 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.149 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'client' failed to build: The command '/bin/sh -c apt-get update -y && apt-get install -y     git     wget     python3.5     python3-pip     python-setuptools     python3-nacl     apt-transport-https     ca-certificates     build-essential     pkg-config     cmake     libssl-dev     libsqlite3-dev     libsodium-dev     curl' returned a non-zero code: 100

**Comment by masterDev1985** [comment]
I'd recommend taking a look at https://forums.docker.com/t/no-space-left-on-device-error/10894/16 or perhaps https://stackoverflow.com/questions/30604846/docker-error-no-space-left-on-device
