### ISSUE TITLE
Issue with docker-ce 18.06

### ISSUE THREAD

**Issue by sunburntcat** [IBM-Blockchain-Identity/indy-ssivc-tutorial#13]
When using docker-ce 18.06 for Ubuntu, running the von-network manage start script results in the following error. This error does NOT appear with docker-ce version 18.03.1  :

> Error response from daemon: unable to insert jump to DOCKER-ISOLATION rule in FORWARD chain:  (iptables failed: iptables --wait -I FORWARD -j DOCKER-ISOLATION: iptables v1.6.0: Couldn’t load target `DOCKER-ISOLATION’:No such file or directory
> 
> Try `iptables -h’ or ‘iptables --help’ for more information.
> (exit status 2))

**Comment by sunburntcat** [comment]
It's suggested the README indicate that there might be some issues with docker-ce and/or the user should use the docker-ce version 18.03.1 to avoid errors.

**Comment by brycecurtis** [comment]
I just build and ran with 18.06.1-ce-mac73 and it works.  I'm not sure if there's a problem with your Docker configuration on Ubuntu, or maybe just Docker on Ubuntu?

**Comment by sunburntcat** [comment]
It may have just been a local Docker issue like you say. I rebooted the Ubuntu box and it went away. I'll close the issue.
