### ISSUE TITLE
Von-web_1 times out while nodes are coming up

### ISSUE THREAD

**Issue by sunburntcat** [IBM-Blockchain-Identity/indy-ssivc-tutorial#16]
When starting the von-network manage script, the following error(s) appear:

von-web_1  | Generated genesis transaction file:
von-web_1  | /home/indy/.indy-cli/networks/sandbox/pool_transactions_genesis
...
von-web_1  | ERROR|indy::services::pool          |           src/services/pool/mod.rs:426 | Pool worker thread finished with error Timeout
von-web_1  | ERROR|indy::errors::indy            |                 src/errors/indy.rs:68  | Casting error to ErrorCode: Timeout
von-web_1  | _indy_loop_callback: Function returned error 307
von-web_1  | Traceback (most recent call last):
von-web_1  |   File "server.py", line 295, in <module>
von-web_1  |     loop.run_until_complete(boot())
von-web_1  |   File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
von-web_1  |     return future.result()
von-web_1  |   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
von-web_1  |     raise self._exception
von-web_1  |   File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
von-web_1  |     result = coro.throw(exc)
von-web_1  |   File "server.py", line 112, in boot
von-web_1  |     await pool.open()
von-web_1  |   File "/home/indy/.local/share/virtualenvs/server-8XoupS0v/lib/python3.5/site-packages/von_agent/nodepool.py", line 125, in open
von-web_1  |     self._handle = await pool.open_pool_ledger(self.name, None)
von-web_1  |   File "/home/indy/.local/share/virtualenvs/server-8XoupS0v/lib/python3.5/site-packages/indy/pool.py", line 82, in open_pool_ledger
von-web_1  |     open_pool_ledger.cb)
von-web_1  |   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
von-web_1  |     yield self  # This tells Task to wait for completion.
von-web_1  |   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
von-web_1  |     future.result()
von-web_1  |   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
von-web_1  |     raise self._exception
von-web_1  | indy.error.IndyError: ErrorCode.PoolLedgerTimeout

**Comment by sunburntcat** [comment]
When digging into the indy-sdk document, I came across this statement, so I'm closing the issue:

Getting a PoolLedgerTimeout error is because the IP addresses in cli/docker_pool_transactions_genesis and the pool configuration don't match.

**Comment by MythriInnovatins** [comment]
I am also facing this issue.Would you please guide me.

**Comment by sunburntcat** [comment]
Brute forcing removal of the running container or deleting the indy network will give the error. Unfortunately I didn't know enough about Docker to debug the issue. The only solution I found was to re-clone von-network from scratch on a clean machine.
