### ISSUE TITLE
localhost:8080 not working correctly

### ISSUE THREAD

**Issue by DanielaNye** [IBM-Blockchain-Identity/indy-ssivc-tutorial#21]
I'm having troubles with localhost:8080, it was working correctly with all features but suddenly it stops working and only let do search, the register button disappear and when trying to acess http://localhost:8080/submit_claim it says Page not found. 
Can you tell me if the services are down or if something happened with my installation?
Thanks

**Comment by DanielaNye** [comment]
Recreating docker_person_1 ... 
Recreating docker_person_1 ... done
Attaching to docker_person_1
person_1           | ----------------------------------------------------------------------------------
person_1           | No command line parameters were provided to the entry point.
person_1           | Using the values specified for the environment, or defaults if none are provided.
person_1           | 
person_1           | TEMPLATE_NAME: person
person_1           | APPLICATION_IP: 0.0.0.0
person_1           | APPLICATION_PORT: 8080
person_1           | INDY_WALLET_SEED: bc_registries_000000000000000000
person_1           | ----------------------------------------------------------------------------------
person_1           | ================================================================================
person_1           | Using template: person
person_1           | Cmd: python manage.py runserver 0.0.0.0:8080
person_1           | ================================================================================
person_1           | Copying template directory; /app/site_templates/person ...
person_1           | ================================================================================
person_1           | Attempting to register our wallet seed 'bc_registries_000000000000000000' at http://von-web:8000/register
person_1           | ================================================================================
person_1           |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
person_1           |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: von-web
person_1           | Starting server ...




I think the problem is here in the permitify.

**Comment by MythriInnovatins** [comment]
How you solve this issue
