### ISSUE TITLE
Manage build is not working for von-network and permityfy

### ISSUE THREAD

**Issue by MythriInnovatins** [IBM-Blockchain-Identity/indy-ssivc-tutorial#22]
Hi,
I tried to build the von-net work and permitify using the command specified in the document.
./manage build.
But it is failing.
I am working in windows pro.Uisng the power shell I executed the command.

Please help me to solve this issue.

Thanks and regards
Hirankumar

**Comment by DanielaNye** [comment]
I'm having the same problem, if you fix it let me know please.

**Comment by MythriInnovatins** [comment]
Sorry for the delay.I solved by rename the file manage to manage.sh.
