### ISSUE TITLE
something wrong with the Dockerfile

### ISSUE THREAD

**Issue by WandyLau** [IBM-Blockchain-Identity/indy-ssivc-tutorial#9]
when I try to build VON with command line : 
    ./manage build. got an error like below:
<img width="670" alt="screen shot 2018-07-05 at 3 30 22 pm" src="https://user-images.githubusercontent.com/2303377/42308627-b5f0e366-8068-11e8-8346-b8990745650f.png">

I am not sure how to correct this. Please help. Thanks in advance.

**Comment by masterDev1985** [comment]
@WandyLau it might be caused by the version of docker that you are using.  If it's too old, it won't support the `chown` flag.

https://stackoverflow.com/questions/44766665/how-do-i-docker-copy-as-non-root

**Comment by WandyLau** [comment]
OK. I have found that cause too. Thanks
